### ISSUE TITLE
Create design for Our Networks 2020

### ISSUE THREAD

**Issue by dcwalk** [ournetworks/2020#15]
## Our Networks 2020 design brief

> Growing Our Networks in Uncertain Times/Places
August 7–9, 2020
Online, Distributed
Based out of UTC-4 from America/Toronto

### Goal
Develop a visual language for Our Networks 2020 that reflects this year’s theme. The outcome from this should be a clear articulation of visual direction to reference in communicating the distributed conference both online and offline. 

### Milestones and timeline
- **April 11:** Design brief
- **April 25:** Co-organizers Design Jam
- **May 2**: Draft/Initial design 
- **May 9:** Design delivery
- **May 18:** Website relaunch
- **June 9:** CFP closes
- **June 26:** Registration, Website re-relaunch
- **July 10–August 9:** Distributed happenings

### Proposed deliverables
A document, and design files, to help guide us from May onwards. This design document should contain:
- [x] Colour palette
- [x] Fonts/Typefaces
- [ ] Layout logic for the placement of content
- [ ] Treatment of imagery
- [ ] Supporting graphics and artwork
- [ ] Concept for a redesign of ournetworks.ca
- [ ] Concept for conference mail-out(s)
- [ ] Concept for digital posters, pin-ups, video bumper, social media
- Stretch:
  - [ ] Concept for program/retrospective
  - [ ] A 2020 version of the Our Networks logo

### Attribution
The designer(s) will be attributed on ournetworks.ca and in the conference program. The deliverables will be archived through our GitHub Artwork repository and licensed under a Creative Commons Attribution-ShareAlike 4.0 International License.

### Appendix and references
- Notes on look-and-feel: https://github.com/ournetworks/2020/issues/17
- [2019 Design Brief](https://docs.google.com/document/d/123645rAxWgXkwDhbjzHAi6UKRJEvR0H3vKb8d3Qq7CQ/edit#heading=h.54ns5pngi9o6)
- https://ournetworks.ca/
- 2020 organizing repository: https://github.com/ournetworks/2020
- https://twitter.com/_ournetworks
- Our Networks artwork repository: https://github.com/ournetworks/artwork
- Previous versions of ournetworks.ca:
  - https://2019.ournetworks.ca/
  - https://2018.ournetworks.ca/
  - https://2017.ournetworks.ca/

**Comment by dcwalk** [comment]
Discussed on `2020-04-18` meeting and seems like we'll shift design delivery and website re-launch a week -- into mid-May

**Comment by garrying** [comment]
## Concept 1:
![01-01](https://user-images.githubusercontent.com/227587/81023485-92c93d80-8e3e-11ea-8ee7-2616897d3579.png)
![01-02](https://user-images.githubusercontent.com/227587/81023488-92c93d80-8e3e-11ea-862e-c8ab973315be.png)
![01-03](https://user-images.githubusercontent.com/227587/81023490-9361d400-8e3e-11ea-80d6-6182c8f1a9ca.png)
![01-04](https://user-images.githubusercontent.com/227587/81023491-9361d400-8e3e-11ea-9871-f20c778c869b.png)
![01-05](https://user-images.githubusercontent.com/227587/81023492-9361d400-8e3e-11ea-9ff9-023af3a0976f.png)
![01-06](https://user-images.githubusercontent.com/227587/81023494-93fa6a80-8e3e-11ea-9ad7-956c1d1bdafb.png)

## Concept 2:
![02-01](https://user-images.githubusercontent.com/227587/81023503-9d83d280-8e3e-11ea-939a-b8afe1d05e4b.png)
![02-02](https://user-images.githubusercontent.com/227587/81023505-9e1c6900-8e3e-11ea-9ba6-51791c8bffd8.png)
![02-03](https://user-images.githubusercontent.com/227587/81023506-9e1c6900-8e3e-11ea-8f9f-34eaabdf8354.png)
![02-04](https://user-images.githubusercontent.com/227587/81023507-9e1c6900-8e3e-11ea-966b-7d31a968c92e.png)
![02-05](https://user-images.githubusercontent.com/227587/81023508-9eb4ff80-8e3e-11ea-9179-9925587ec99f.png)
View this comp at actual size. The supporting imagery should be rough with no anti-aliasing.
![02-06](https://user-images.githubusercontent.com/227587/81023509-9eb4ff80-8e3e-11ea-88ae-56a831448016.png)

**Comment by RangerMauve** [comment]
I like them! Definitely vibing with the Concept 2 the strongest. 😻

**Comment by dcwalk** [comment]
Notes from `2020-05-09` call: 

- Want to spend time on another iteration, in one or both depending on where we do that
- Want to see if how the 
- Shift in website navigation 
- Concept: "the green one"
    - 3D generative imagry (musuem objects that are scanned)
        - http://threedscans.com/
    - how to represent time (some interactive way to select timezone)
        - dc: can it be two way?
    - evolving oval based on UNIX timestamp
    - timezones visualized in some way (or a representated in some way)
    - 3d objects 
    - dc: love the green!
- Concept 2: transforming fun
    - metaflop font
    - title heading changing over time using metaflop generation at a set cadence
    - content area 
    - more emphasis on typographic v. colour treatment
    - threshhold webtool + narrow colour palette to add texture
- sarah: vibing with 1, love metaflop
    - layout feels fresh, big departure
    - vibe 2 for: colour from 2 reminds of year two (retro for ournetws as an org)
- mauve: vibing with 2, images especially
- dc: love both, want them to do both! 
    - colour from green -> into images?
    - image treatment from 2 vibing with
    - what about changing the content background colour?
- garry:
    - concerns with de-emphasizing logo?
    - want feedback in the design issue 
        - #todo dc: to paste in
        - #todo others add theirs in!

**Comment by dcwalk** [comment]
Notes 2020-06-06: still need a deck/document to help define. PR'd artwork repo, developed along with next iteration of website.

**Comment by ana0** [comment]
Sad to close this because it's awesome but would say it's pretty much done
