### ISSUE TITLE
Sponsorship outreach

### ISSUE THREAD

**Issue by dcwalk** [ournetworks/2020#22]
Building on #7 we need to do outreach to sponsors

## Todos

- [x] asks
   - [x] dc: initial wave to previous top three 
   - [x] more broadly from previous list
- [x] identify
  - [x] from conf tools 
  - [x] from community
- [x] first-wave outreach
- [x] second-wave outreach
